#!/bin/bash
if ! [ -e $HOME/nanoc-site ]; then
    echo "$HOME/nanoc-site doesn't exist"
    exit 0
fi

if [ $# -ge 1 ]; then
   if [ "$1" == "restart" ]; then
       kill -9 `pgrep -f ".*nanoc view -p 3000"`
       $HOME/git-repo/config/script/common/run_cron.sh nanoc-public nanoc-public
       exit 0
   else
       echo "invalid parameter"
       exit 1
   fi
fi

cd $HOME/nanoc-site && nanoc view -p 3000
