#!/bin/bash
source ~/.bash_environment_setup
if [ -n "$NANOC_PUBLIC_SITE" ] && [ -e $NANOC_PUBLIC_SITE ]; then
    if ! pgrep -f ".*nanoc view -p 3000" 1>/dev/null 2>&1; then
        cd $NANOC_PUBLIC_SITE && nanoc view -p 3000
    else
        echo "already a running nanoc-public"
    fi
fi
